# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
   Welcome App-Choreographer 👋! Thank you for submitting this issue! Our team will be with you very shortly! Thank you!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thank you for opening this Pull Request dear App-Choreographer! It is greatly appreciated! We will be with you to review this very shortly! Thank you!

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats! PR merged successfully! Keep contributing App-Choreographer! Thank you! 🥳🎉

# It is recommended to include as many gifs and emojis as possible!